
// this file is automatically generated by git.version.ts script
export const applicationversion = {
  version: '0.0.0',
  revision: 'cdb7863',
  branch: 'main',
  date: 'Sun Jan 10 08:56:47 2021 +0100'
};