
// this file is automatically generated by git.version.ts script
export const applicationversion = {
  version: '0.0.0',
  revision: '9c6b853',
  branch: 'main',
  date: 'Fri Jan 8 13:26:30 2021 +0100'
};