
// This file is automatically generated by git.version.ts script
export const applicationversion = {
  version: '2.50.0',
  revision: '4c64671',
  branch: 'main',
  date: 'Tue Feb 2 21:50:02 2021 +0100'
};